id: PE57C5CC9
initial_creation_type: input
source_metadata:
  Title: Santānāntarasiddhi kārikā ṭīkā
  Editor: Negi, J.S.
  Publisher: Central Institute of Higher Tibetan Studies
  Place of Publication: Sarnath
  Year: '1997'
  Santānāntarasiddhiṭīkā:
    Text Version: Romanized
    Input Personnel: DSBC Staff
    Input Date: '2007'
    Proof Reader: Milan Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
created_at: '2022-03-08T16:50:35.063699'
last_modified_at: '2022-03-08T16:50:35.063707'
